### PR TITLE
Add `wibo.sha1` to release and artifact

### PR DESCRIPTION
**Pull request by ribbanya**

### CODE REVIEW

**Comment by simonlindholm** [comment]
Fine with me, but curious about the reason?

**Comment by ribbanya** [comment]
[Melee CLI](https://github.com/doldecomp/melee/blob/7b4429888586a68788938476bf86ee44824b2360/.github/workflows/build.yml#L27).

**Comment by simonlindholm** [comment]
Why do you need to check the sha1 in melee CI? If for reasons of pinning a specific version and checking that it doesn't change, which I can totally get behind, downloading the sha1 hash for the same source as the wibo binary doesn't help...

**Comment by ribbanya** [comment]
Idk our other downloads are behind zips which have their own checksums. TCP is probably completely fine but it seemed reasonable to also check the sha.

**Comment by simonlindholm** [comment]
It's not just TCP, it's also HTTPS, which comes with built-in signature checking. So the only thing you're really protecting against is bad storage on GitHub's (Azure's) side, which I'm fairly sure they have mechanisms in place to protect against because Azure is a serious cloud platform (and I've never heard of anyone having problems with it).

**Comment by ribbanya** [comment]
Ah, okay. Well I leave the decision to merge up to you.

**Comment by mkst** [comment]
I get the sentiment of checking random binaries downloaded off the internet before running them on your own computer. The way I see it, the potential risk here is that *we* (or bad actor acting as decompals) replace the `wibo` binary with something nasty that, let's say, tries to take all environment variables (i.e. if you have any SECRETS) and POSTs them off to us.

There is no harm in you guys confirming the SHA1 checksum of the binary before executing it, but I don't know that it adds any value to *this* project release - anyone with write access to this repo could replace the `wibo` binary with something nasty AND update the sha1 file.

**Comment by simonlindholm** [comment]
I say we close this, then.

**Pull request closed without merging**
